### PRUEBAS
GET http://localhost:4005/rings-api/admin/doLogin2


### LOGIN
POST http://localhost:4005/rings-api/admin/doLogin
content-type: application/json

{
    "user": "params.user",
    "password": "params.password"
}


### CONSULTAR RFC
GET http://localhost:4005/pdrservice/ticketAPI/consultarRFC